# ############################################################################
# model: Seq2Seq
# encoder: CRDNN model
# decoder: GRU + beamsearch + Transformer
# tokens: BPE
# losses: CTC+NLL
# training: 
# authors: Ruhr-University Bochum 2021
#          adapted from 
#            Ju-Chieh Chou, 
#            Mirco Ravanelli,
#            Abdel Heba,
#            Peter Plantinga,
#            Samuele Cornell, 
#            Sung-Lin Yeh, 
#            Titouan Parcollet 2021
# ############################################################################

# set exp name
name: CRDNN

# set toch seed
seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# define all input paths and files

## database paths
data_folder: /home/<username>/database/processed/sets/

## noise/ris dataset will automatically be downloaded
data_folder_rirs: /home/<username>/database/processed/rirs_noises/

## tokenizer path
pretrained_tokenizer: ../tokenizer/results/tokenizer_unigram_5000/5000_unigram.model

## datasets (train & dev will be concatenated)
train_sets: ["mcv-train.json", "mai-train.json", "swc-train.json"]
dev_sets: ["mcv-dev.json", "mai-dev.json", "swc-dev.json"]
test_sets: ["mcv-test.json", "mai-test.json", "swc-test.json"]

# define all output paths and files

## model and logging
output_folder: !ref results/<name>/<seed>
set_folder: !ref <output_folder>/sets
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

## temporary files for database concatenation
train_csv: !ref <set_folder>/train.csv
valid_csv: !ref <set_folder>/dev.csv
test_csv:
   - !ref <set_folder>/mcv-test.csv
   - !ref <set_folder>/mai-test.csv
   - !ref <set_folder>/swc-test.csv
   
# General training parameters
ckpt_interval_minutes: 25
number_of_epochs: 40 
number_of_ctc_epochs: 40
batch_size: 12 
lr: 1.0
ctc_weight: 0.5
sorting: ascending


# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40


# Optimizer
opt_class: !name:torch.optim.Adadelta
   lr: !ref <lr>
   rho: 0.95
   eps: 1.e-8

# Dataloader options
train_dataloader_opts:
   batch_size: !ref <batch_size>

valid_dataloader_opts:
   batch_size: !ref <batch_size>

test_dataloader_opts:
   batch_size: 1

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (64, 128)
inter_layer_pooling_size: (2, 2)
cnn_kernelsize: (3, 3)
time_pooling_size: 4
rnn_class: !name:speechbrain.nnet.RNN.LSTM
rnn_layers: 4
rnn_neurons: 1024
rnn_bidirectional: True
dnn_blocks: 1
dnn_neurons: 1024
emb_size: 1024
dec_neurons: 1024
output_neurons: 5000  # Number of tokens (same as LM and tokenizer)
blank_index: 0
pad_index: -1
bos_index: 1
eos_index: 2
unk_index: 0

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
valid_beam_size: 20
test_beam_size: 40
eos_threshold: 1.5
using_max_attn_shift: True
max_attn_shift: 300
ctc_weight_decode: 0.40
ctc_window_size: 200
coverage_penalty: 1.5
temperature: 1.0


# Feature Extraction
normalize: !new:speechbrain.processing.features.InputNormalization
   norm_type: global

compute_features: !new:speechbrain.lobes.features.Fbank
   sample_rate: !ref <sample_rate>
   n_fft: !ref <n_fft>
   n_mels: !ref <n_mels>

# Data augmentation
env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
   openrir_folder: !ref <data_folder_rirs>
   babble_prob: 0.0
   reverb_prob: 0.0
   noise_prob: 1.0
   noise_snr_low: 0
   noise_snr_high: 15

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
   sample_rate: !ref <sample_rate>
   speeds: [95, 100, 105]

# Tokenizer
tokenizer: !new:sentencepiece.SentencePieceProcessor

# Encoder
enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
   input_shape: [null, null, !ref <n_mels>]
   activation: !ref <activation>
   dropout: !ref <dropout>
   cnn_blocks: !ref <cnn_blocks>
   cnn_channels: !ref <cnn_channels>
   cnn_kernelsize: !ref <cnn_kernelsize>
   inter_layer_pooling_size: !ref <inter_layer_pooling_size>
   time_pooling: True
   using_2d_pooling: False
   time_pooling_size: !ref <time_pooling_size>
   rnn_class: !ref <rnn_class>
   rnn_layers: !ref <rnn_layers>
   rnn_neurons: !ref <rnn_neurons>
   rnn_bidirectional: !ref <rnn_bidirectional>
   rnn_re_init: True
   dnn_blocks: !ref <dnn_blocks>
   dnn_neurons: !ref <dnn_neurons>
   use_rnnp: True

# Decoder
emb: !new:speechbrain.nnet.embedding.Embedding
   num_embeddings: !ref <output_neurons>
   embedding_dim: !ref <emb_size>
   
dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
   enc_dim: !ref <dnn_neurons>
   input_size: !ref <emb_size>
   rnn_type: gru
   attn_type: location
   hidden_size: !ref <dec_neurons>
   attn_dim: 1024
   num_layers: 1
   scaling: 1.0
   channels: 10
   kernel_size: 100
   re_init: True
   dropout: !ref <dropout>

# Losses
log_softmax: !new:speechbrain.nnet.activations.Softmax
   apply_log: True
   
ctc_lin: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <dnn_neurons>
   n_neurons: !ref <output_neurons>

seq_lin: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <dec_neurons>
   n_neurons: !ref <output_neurons>

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
   blank_index: !ref <blank_index>

seq_cost: !name:speechbrain.nnet.losses.nll_loss
   label_smoothing: 0.1

# Compile model
modules:
   enc: !ref <enc>
   emb: !ref <emb>
   dec: !ref <dec>
   ctc_lin: !ref <ctc_lin>
   seq_lin: !ref <seq_lin>
   normalize: !ref <normalize>
   env_corrupt: !ref <env_corrupt>

model: !new:torch.nn.ModuleList
   - [!ref <enc>, !ref <emb>, !ref <dec>, !ref <ctc_lin>, !ref <seq_lin>]

# Beam searcher
valid_search: !new:speechbrain.decoders.S2SRNNBeamSearcher
   embedding: !ref <emb>
   decoder: !ref <dec>
   linear: !ref <seq_lin>
   ctc_linear: !ref <ctc_lin>
   bos_index: !ref <bos_index>
   eos_index: !ref <eos_index>
   blank_index: !ref <blank_index>
   min_decode_ratio: !ref <min_decode_ratio>
   max_decode_ratio: !ref <max_decode_ratio>
   beam_size: !ref <valid_beam_size>
   eos_threshold: !ref <eos_threshold>
   using_max_attn_shift: !ref <using_max_attn_shift>
   max_attn_shift: !ref <max_attn_shift>
   coverage_penalty: !ref <coverage_penalty>
   temperature: !ref <temperature>

# Use the same BeamSearcher as in the validation phase
# TODO for later: try to train a LM on german text and use it here
# with !new:speechbrain.decoders.S2SRNNBeamSearchLM
# also add it to the <pretrainer> block (via path and loadables)
# and add it to the modules list
test_search: !ref <valid_search>

# Training schedule, logging and stopping
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
   limit: !ref <number_of_epochs>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr>
   improvement_threshold: 0.0025
   annealing_factor: 0.8
   patient: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_folder>
   recoverables:
      model: !ref <model>
      scheduler: !ref <lr_annealing>
      normalizer: !ref <normalize>
      counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
   split_tokens: True

# Load pretrained models
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
   collect_in: !ref <save_folder>
   loadables:
      tokenizer: !ref <tokenizer>
   paths:
      tokenizer: !ref <pretrained_tokenizer>
